# Generated by Django 5.1.5 on 2025-02-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_product_f_vencimiento_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='pais',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
